Apps/incomeExpence/urls.py
from django.urls import path
from . import views as v

app_name = "incomeExpense"
urlpatterns = [
    
    # INCOME SOURCE PATHS
    
    path('income/source/list/', v.incomeSourceListView.as_view(), name="incomeSourceList"),
    path('income/source/add/', v.incomeSourceAddView.as_view(), name="incomeSourceAdd"),
    path('income/source/search/', v.incomeSourceSearchView.as_view(), name="incomeSourceSearch"),
    path('income/source/<slug:slug>/update/', v.incomeSourceUpdateView.as_view(), name="incomeSourceUpdate"),
    path('income/source/<slug:slug>/delete/', v.incomeSourceDeleteView.as_view(), name="incomeSourceDelete"),
    
    # INCOME  PATHS
    
    path('income/add/', v.incomeAddView.as_view(), name="incomeAdd"),
    path('income/list/', v.incomeListView.as_view(), name="incomeList"),
    path('income/search/', v.incomeSearchView.as_view(), name="incomeSearch"),
    path('income/<int:id>/update/', v.incomeUpdateView.as_view(), name="incomeUpdate"),
    path('income/<int:id>/delete/', v.incomeDeleteView.as_view(), name="incomeDelete"),
    
    # EXPENSE SOURCE PATHS
    
    path('expense/source/add/', v.expenseSourceAddView.as_view(), name="expenseSourceAdd"),
    path('expense/source/list/', v.expenseSourceListView.as_view(), name="expenseSourceList"),
    path('expense/source/search/', v.expenseSourceSearchView.as_view(), name="expenseSourceSearch"),
    path('expense/source/<slug:slug>/update/', v.expenseSourceUpdateView.as_view(), name="expenseSourceUpdate"),
    path('expense/source/<slug:slug>/delete/', v.expenseSourceDeleteView.as_view(), name="expenseSourceDelete"),
    
    
    
    # EXPENSE  PATHS
    path('expense/add/', v.expenseAddView.as_view(), name="expenseAdd"),
    path('expense/list/', v.expenseListView.as_view(), name="expenseList"),
    path('expense/search/', v.expenseSearchView.as_view(), name="expenseSearch"),
    path('expense/<int:id>/update/', v.expenseUpdateView.as_view(), name="expenseUpdate"),
    path('expense/<int:id>/delete/', v.expenseDeleteView.as_view(), name="expenseDelete"),
    
]

FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='account')),
    path('account/', include('allauth.urls')),
    path('employee/', include('Apps.employees.urls', namespace="employees")),
    path('core/', include('Apps.core.urls', namespace="core")),
    path('income-expense/', include('Apps.incomeExpence.urls', namespace="incomeExpense")),
    path('offender/', include('Apps.offender.urls')),
    path('complaint/', include('Apps.complaints.urls')),
    path('wood/', include('Apps.wood.urls', namespace="wood")),
    path('employee/', include('Apps.report.urls', namespace="report")),
    path('', homeView.as_view(), name="home")
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/incomeExpence/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse_lazy as _
from django.db.models import Sum
from datetime import datetime
from django.utils.timezone import now
# Create your models here.

class IncomeSource(models.Model):
    
    name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(max_length=60, unique=True)
    
    
    def __str__(self):
        return self.name
    
    
    def save(self, *args, **kwargs):
        
        self.slug = slugify(self.name)
        
        super(IncomeSource, self).save(args, kwargs)


class Income(models.Model):
    
    source = models.ForeignKey(to="IncomeSource", on_delete=models.CASCADE, related_name="incoms")
    amount = models.IntegerField()
    date = models.DateField(default=now)
    description = models.TextField(max_length=200, null=True, blank=True)

    @property
    def getTotal(self):
        
        return Income.objects.aggregate(total=Sum('amount'))['total']
        
        


class ExpenseSource(models.Model):
    
    name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(max_length=60, unique=True)
    
    
    def __str__(self):
        return self.name
    
    
    def save(self, *args, **kwargs):
        
        self.slug = slugify(self.name)
        
        super(ExpenseSource, self).save(args, kwargs)


class Expense(models.Model):
    
    source = models.ForeignKey(to="ExpenseSource", on_delete=models.CASCADE, related_name="expenses")
    amount = models.IntegerField()
    date = models.DateField(default=now)
    description = models.TextField(max_length=200, null=True, blank=True)
    
    @property
    def getTotal(self):
        
        return Expense.objects.aggregate(total=Sum('amount'))['total']

Apps/incomeExpence/forms.py
from django import forms
from .models import IncomeSource, ExpenseSource, Income, Expense
from crispy_forms.helper import FormHelper

class IncomeSourceForm(forms.ModelForm):
    """
    INCOME SOURCE FORM
    """
    class Meta:
        
        model = IncomeSource
        fields = '__all__'
        exclude = ['slug']

    
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False


class IncomeForm(forms.ModelForm):
    """
    INCOME  FORM
    """
    class Meta:
        
        model = Income
        fields = '__all__'
    
        widgets = {
            'date': forms.DateInput(attrs={'type':'date'})
        }
    
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        

class ExpenseForm(forms.ModelForm):
    """
    EXPENSE  FORM
    """
    class Meta:
        
        model = Expense
        fields = '__all__'
        
        widgets = {'date': forms.DateInput(attrs={'type':'date'})}
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        
        
        

class ExpenseSourceForm(forms.ModelForm):
    """
    EXPENSE SOURCE FORM
    """
    class Meta:
        
        model = ExpenseSource
        fields = '__all__'
        exclude = ['slug']
    
    
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False

Apps/incomeExpence/views.py
from django.shortcuts import render,HttpResponse
from .forms import IncomeSourceForm, ExpenseSourceForm, IncomeForm, ExpenseForm
from .models import IncomeSource, ExpenseSource, Income, Expense
from django.views import View
from django.views.generic import ListView
from django.contrib import messages
from time import sleep
from django.http import Http404
from django.core.paginator import Paginator
from django.db.models import Q
from render_block import render_block_to_string
from django.shortcuts import get_object_or_404
from django.contrib.auth.hashers import check_password
from django.views.generic import CreateView
from Apps.core.views import hx_Redirect
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def get_template(request, name, path):
    
    if request.htmx:
        return f'{path}/partials/{name}.html'
    
    return f'{path}/{name}.html'




"""
********************************************** INCOME SOURCE **********************************************
"""

class incomeSourceAddView(LoginRequiredMixin,View):
        
    """
    Income Source CREATE VIEW
    """
    
    def get(self, request):
        
        print("i am okay bro")
        context = {'form': IncomeSourceForm(),'heading':'Add Income Source'}
        template = get_template(request, 'source_add', path="incomesource")
        print("i am okay bro")
        
        return render(request,template, context )
    
    
    def post(self, request):
        
        
        form = IncomeSourceForm(data=request.POST)
        if form.is_valid():
            
            form.save()
            form = IncomeSourceForm()
            
            messages.success(request, "Data Addedd Successfully")
            return hx_Redirect("incomeExpense:incomeSourceList")
        else:
            messages.error(request, "Please Correct the error bellow")
        
        template = get_template(request, 'source_add', path="incomesource")
        
        context = {'form': form}
        return render(request,template, context)
    
    

class incomeSourceListView(LoginRequiredMixin,ListView):
    
    """
    INCOME SOURCE LIST VIEW
    """
    model = IncomeSource
    context_object_name = 'sources'
    paginate_by = 10
    paginate_orphans = 0
    
    def get_template_names(self): return get_template(self.request, 'source_list', path="incomesource")
    
    def get_queryset(self):
        return IncomeSource.objects.all()
    
    def paginate_queryset(self, queryset, page_size):
        
        try:
            
            return super(incomeSourceListView, self).paginate_queryset(queryset, page_size)
        except Http404:
            
            self.kwargs['page'] = 1
            return super(incomeSourceListView, self).paginate_queryset(queryset, page_size)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["isSearch"] = False
        return context



class incomeSourceSearchView(LoginRequiredMixin,View):
    """
    INCOME SOURCE SEARCHE VIEW
    """
    
    def get(self, request):
        
        page_number = request.GET.get('page', 1)
        query = request.GET.get('query')
        
        if query is None:
            query = ""
        
        incomeSource = IncomeSource.objects.filter(Q(name__istartswith=query)).order_by('pk')
        paginator = Paginator(incomeSource, per_page=10)
        
        
        
        page = paginator.get_page(page_number)
        
        context={
            
            'sources': page.object_list,
            'page_obj': page,
            'isSearch': True
        
        }
        
        response = render_block_to_string(get_template(request,'source_list', path="incomesource"), 'table', context)
        
        
        return HttpResponse(response)
    

class incomeSourceUpdateView(LoginRequiredMixin,View):
    """
    INCOME SOURCE UPDATE VIEW
    """

    def get(self, request, slug):
        
        incomesource = get_object_or_404(IncomeSource, slug=slug)
        form = IncomeSourceForm(instance=incomesource)
        context = {'form':form, 'heading':'Update Income Source','isUpdate':True, 'object': incomesource}
        template_name = get_template(request, 'source_add', path="incomesource")
        
        return render(request, template_name, context)
    
    def post(self, request, slug):
        
        incomesource = get_object_or_404(IncomeSource, slug=slug)
        form = IncomeSourceForm(instance=incomesource, data=request.POST)
        
        if form.is_valid():
            
            incomesource = form.save()
            messages.success(request, f'{incomesource} Update Successfully')
            return hx_Redirect("incomeExpense:incomeSourceList")
        else:
            messages.error(request, 'Please correct the Error Bellow')
        
        context = {'form':form, 'heading':'Update Income Source','isUpdate':True, 'object': incomesource}
        template_name = get_template(request, 'source_add', path="incomesource")
        
        return render(request,template_name, context)




class incomeSourceDeleteView(LoginRequiredMixin,View):
    
    """
    INCOME SOURCE DELETE VIEW
    """
    def get(self, request, slug):
       
        try:
            
            incomesource = get_object_or_404(IncomeSource, slug=slug)
            
            context = {'object': incomesource, 'msg': f'Are you sure you want to delete  <strong> <i>{incomesource.name}</i></strong>? This action cannot be undone.'}
            
            return render(request,get_template(request, 'delete', path="incomesource"), context)
        

        except Http404:
            
            
            return render(request, get_template(request, '404', path="incomesource")) 
    
    
    
    def post(self, request, slug):
        

        incomesource = get_object_or_404(IncomeSource, slug=slug)


        
        incomesource.delete()
        messages.success(request, f'{incomesource.name} deleted successfully')

        return hx_Redirect("incomeExpense:incomeSourceList")
        # context = {'isDeleted': True,'msg': f'{incomesource.name} deleted Successfully'}
        # return render(request, get_template(request, 'delete', path="incomesource"), context)





"""
********************************************** EXPENSE SOURCE **********************************************
"""



class expenseSourceAddView(LoginRequiredMixin,View):
        
    """
    EXPENSE SOURCE CREATE VIEW
    """
    
    def get(self, request):
        
        context = {'form': ExpenseSourceForm(),'heading':'Add Income Source'}
        template = get_template(request, 'source_add', path="expensesource")
        return render(request,template, context )
    
    
    def post(self, request):
        
        
        form = ExpenseSourceForm(data=request.POST)
        if form.is_valid():
            
            form.save()
            form = ExpenseSourceForm()
            
            messages.success(request, "Data Addedd Successfully")
            return hx_Redirect("incomeExpense:expenseSourceList")
        else:
            messages.error(request, "Please Correct the error bellow")
        
        template = get_template(request, 'source_add', path="expensesource")
        
        context = {'form': form}
        return render(request,template, context)
    
    

class expenseSourceListView(LoginRequiredMixin,ListView):
    
    """
    EXPENSE SOURCE LIST VIEW
    """
    model = ExpenseSource
    context_object_name = 'sources'
    paginate_by = 10
    paginate_orphans = 0
    
    def get_template_names(self): return get_template(self.request, 'source_list', path="expensesource")
    
    def get_queryset(self):
        return ExpenseSource.objects.all()
    
    def paginate_queryset(self, queryset, page_size):
        
        try:
            
            return super(expenseSourceListView, self).paginate_queryset(queryset, page_size)
        except Http404:
            
            self.kwargs['page'] = 1
            return super(expenseSourceListView, self).paginate_queryset(queryset, page_size)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["isSearch"] = False
        return context



class expenseSourceSearchView(LoginRequiredMixin,View):
    """
    EXPENSE SOURCE SEARCHE VIEW
    """
    
    def get(self, request):
        
        page_number = request.GET.get('page', 1)
        query = request.GET.get('query')
        
        if query is None:
            query = ""
        
        expenseSource = ExpenseSource.objects.filter(Q(name__istartswith=query)).order_by('pk')
        paginator = Paginator(expenseSource, per_page=10)
        
        
        
        page = paginator.get_page(page_number)
        
        context={
            
            'sources': page.object_list,
            'page_obj': page,
            'isSearch': True
        
        }
        
        response = render_block_to_string(get_template(request,'source_list', path="expensesource"), 'table', context)
        
        
        return HttpResponse(response)
    

class expenseSourceUpdateView(LoginRequiredMixin,View):
    """
    EXPENSE SOURCE UPDATE VIEW
    """

    def get(self, request, slug):
        
        expensesource = get_object_or_404(ExpenseSource, slug=slug)
        form = ExpenseSourceForm(instance=expensesource)
        context = {'form':form, 'heading':'Update Expense Source','isUpdate':True, 'object': expensesource}
        template_name = get_template(request, 'source_add', path="expensesource")
        
        return render(request, template_name, context)
    
    def post(self, request, slug):
        
        expensesource = get_object_or_404(ExpenseSource, slug=slug)
        form = ExpenseSourceForm(instance=expensesource, data=request.POST)
        
        if form.is_valid():
            

Apps/incomeExpence/templates/expensesource/partials/source_add.html
{% load crispy_forms_tags %}
{% load static %}
{% include "utils/messages.html" %}

  <div class="content container-fluid">
    <div class="page-header">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-sub-header">
            <h3 class="page-title">{{heading}}</h3>
            <ul class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="../index.html">Home</a>
                
              </li>
              <li class="breadcrumb-item"><a href="#" hx-target="#MDI" hx-push-url="{% url 'incomeExpense:expenseSourceList' %}" hx-get="{% url 'incomeExpense:expenseSourceList' %}">Expense Source</a></li>
              <li class="breadcrumb-item active">{% if isUpdate %} Expense Source Update {% else %}  Expense Source Add {% endif %}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header mb-3">
            <h5 class="card-title">Enter Expense Source Information</h5>
          </div>
          <div class="card-body">
            <form action="." hx-target="#MDI" {% if isUpdate %} hx-post="{% url 'incomeExpense:expenseSourceUpdate' object.slug %}" {% else %} hx-post="{% url 'incomeExpense:expenseSourceAdd' %}" {% endif %} >
              {% csrf_token %}
              <div class="row">
                <div class="col-xl-12">
                  <div class="form-group row">
                    <label class="col-lg-3 col-form-label">{{form.name.label}}</label>
                    <div class="col-lg-9">
                      {{form.name|as_crispy_field}}
                    </div>
                  </div>
                
                </div>
              </div>

              <div class="text-end">
                <button type="submit"  class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>


  {% include 'utils/acceptOnlyChars.html' %}
  <script>
    acceptOnlyChars(['id_name']);
  </script>

Apps/incomeExpence/templates/expensesource/partials/source_list.html
{% load fmsTemplateTag %}
<div class="content container-fluid">
  <div class="page-header">
    <div class="row">
      <div class="col-sm-12">
        <div class="page-sub-header">
          <h3 class="page-title">Expense Source</h3>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active">Expense Source</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- === TABLE === -->

  <div class="row">
    <div class="col-sm-12">
      <div class="card card-table comman-shadow">
        <div class="card-body">
          <div class="page-header">
            <div class="row align-items-center">
              <div class="col">
                <div class="m-0 top-nav-search">
                    <form>
                        <input type="text" id="search" class="form-control" placeholder="Search here">
                        <button hx-vals="js:{'query': get_search_val()}"  hx-get="{% url 'incomeExpense:expenseSourceSearch' %}"   hx-target="#tableMDI" class="btn" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                    
                </div>
              </div>
              <div class="col-auto text-end float-end ms-auto download-grp">
                <a href="#" hx-target="#MDI" hx-push-url="{% url 'incomeExpense:expenseSourceAdd' %}" hx-get="{% url 'incomeExpense:expenseSourceAdd' %}" class="btn btn-primary"
                  ><i class="fas fa-plus"></i
                ></a>
              </div>
            </div>
          </div>
        <div id="tableMDI">
            {% block table %}
          <div class="table-responsive">
            <div
              id="DataTables_Table_0_wrapper"
              class="dataTables_wrapper dt-bootstrap4 no-footer"
            >
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table class="table border-0 star-student table-hover table-center mb-0  no-footer" role="grid">
                    <thead class="">
                      <tr role="row">
                        
                        <th>#</th>
                        <th>Name </th>
                       
                       <th class="text-end">Action </th>
                      </tr>
                    </thead>
                    <tbody>
                        
                        {% for source in sources %}
                            <tr role="row" class="{% if forloop.counter|isOdd %} incomeExpnseodd {% else %} even {% endif %}">
                                <td>{{forloop.counter}}</td>
                                
                                <td>{{source.name}}</td>
                                  
                                <td class="text-end">
                                <div class="actions">
                                    <a
                                    href="javascript:;"
                                    class="btn btn-sm bg-success-light me-2"
                                    hx-get="{% url 'incomeExpense:expenseSourceDelete' source.slug %}"
                                    hx-push-url="{% url 'incomeExpense:expenseSourceDelete' source.slug %}"
                                    hx-target="#MDI"
                                    >
                                    <i class="feather-eye"></i>
                                    </a>
                                    <a
                                    href="#"
                                    class="btn btn-sm bg-danger-light"
                                    hx-get="{% url 'incomeExpense:expenseSourceUpdate' source.slug %}"
                                    hx-push-url="{% url 'incomeExpense:expenseSourceUpdate' source.slug %}"
                                    hx-target="#MDI"
                                    >
                                    <i class="feather-edit"></i>
                                    </a>
                                </div>
                                </td>
                            </tr>
                        {% endfor %}
                            

                   
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="row">
                
                            <!-- Pagination -->
                        {% if not isSearch %}
                        <div class="col-12 d-flex justify-content-end my-3">
                            <nav>
                                <ul class="pagination">
                                
                                
                                {% if  page_obj.has_previous %}
                                    <li class="paginate_button  page-item ">
                                    <a class="page-link "  href="#"  hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page_obj.previous_page_number }}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page_obj.previous_page_number }}" hx-target="#MDI" hx-swap="innerHTML" tabindex="-1" aria-disabled="true">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="paginate_button  page-item disabled">
                                    <a class="page-link " href="#" tabindex="-1" aria-disabled="true">Previous</a>
                                    </li>
                                {% endif %}
                                
                                
                                {% for page in page_obj.paginator %}


                                    {% if page.number < 5 and  page_obj.number < 5 %}
                                    
                                    <li class="paginate_button  page-item   {% if page.number == page_obj.number %} active {% endif %} ">
                                        <a class="page-link "  href="#"  hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                    </li> 
                                    {% endif %}
                                    

                                    {% if page.number >= 5 and page.number == page_obj.number %}
                                    
                                    <li class="paginate_button  page-item ">
                                    <a class="page-link " href="#"  hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page=1" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{1}}" hx-target="#MDI" hx-swap="innerHTML">1</a>
                                    </li>

                                    <li class=" paginate_button  page-item disabled">
                                        <a class="page-link " href="#">...</a>
                                    </li>
                                    
                                    <li class=" paginate_button page-item ">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page_obj.number|add:-1}}" hx-target="#MDI" hx-swap="innerHTML">{{page_obj.number|add:-1 }}</a>
                                    </li>
                                    
                                    <li class=" paginate_button page-item {% if page.number == page_obj.number %} active {% endif %} ">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                    </li>
                                    
                                    {% if page_obj.number < page_obj.paginator.num_pages %}
                                    <li class=" paginate_button  page-item">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page_obj.number|add:1}}" hx-target="#MDI" hx-swap="innerHTML">{{page_obj.number|add:1 }}</a>
                                    </li>
                                    {% endif %}
                                    
                                    
                                    {% endif %}
                                    
                                    
                                    {% if forloop.last and  page.number != page_obj.number and page_obj.number|add:1 < page_obj.paginator.num_pages %}
                                    <li class="paginate_button  page-item disabled">
                                        <a class="page-link" href="#">...</a>
                                    </li>
                                    
                                        <li class="paginate_button  page-item">
                                        <a class="page-link "  href="#" hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                        </li>
                                    {% endif %}
                                    
                                    
                                {% endfor %}
                                    
                                
                                
                                {% if page_obj.has_next %}
                                    <li class=" paginate_button page-item">
                                    <a class="page-link "  href="#" hx-target="#MDI" hx-push-url="{% url 'incomeExpense:expenseSourceList' %}?page={{page_obj.next_page_number}}" hx-get="{% url 'incomeExpense:expenseSourceList' %}?page={{page_obj.next_page_number}}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="paginate_button  page-item disabled">
                                        <a class="page-link" href="#">Next</a>
                                    </li>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% else %}
                        {% include "expensesource/partials/search_pagination.html" %}
                    {% endif %}

                    {% comment %} {% include "utils/list_icons.html" %} {% endcomment %}
              </div>

              </div>
            </div>
          </div>

          


          {% endblock table %}
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'utils/messages.html' %}
{% include 'utils/changeUrl.html' %}
<script>
changeURL('{% url "incomeExpense:expenseSourceList" %}')
</script>
<script>
  
    function get_search_val(){
  
      let search = document.getElementById('search').value
      
      return search
    
    }
  </script>