Apps/employees/urls.py
from django.urls import path
from . import views
app_name="employee"

urlpatterns = [
    
    path("add/", views.empAddView.as_view(), name="empAdd"),
    path("list/", views.empListView.as_view(), name="empList"),
    path("search/", views.empSearchView.as_view(), name="empSearch"),
    path("update/<int:pk>/", views.empUpdateView.as_view(), name="empUpdate"),
    path("delete/<int:pk>/", views.empDeleteView.as_view(), name="empDelete"),
    
    
    # Visits
    path("visit/add/", views.visitAddView.as_view(), name="visitAdd"),
    path("visit/list/", views.visitListView.as_view(), name="visitList"),
    path("visit/update/<int:pk>", views.visitUpdateView.as_view(), name="visitUpdate"),
    path("visit/delete/<int:pk>", views.visitDeleteView.as_view(), name="visitDelete"),
    
    
]

Apps/report/urls.py
from django.urls import path
from . import views
app_name="report"
urlpatterns = [
    path("report/employee",views.emplyee_Report_View, name="employeeReport"),
    path("report/visit/",views.visit_Report_View, name="visitReport"),
    path("report/offender/",views.offender_Report_View, name="offenderReport"),
    path("report/wood/",views.wood_Report_View, name="woodReport"),
    path("report/tree-Altment/",views.TreeAltment_Report_View, name="treeAltmentwoodReport"),
    path("report/complaints/",views.Complaints_Report_View, name="complaintsReport"),
]

FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='account')),
    path('account/', include('allauth.urls')),
    path('employee/', include('Apps.employees.urls', namespace="employees")),
    path('core/', include('Apps.core.urls', namespace="core")),
    path('income-expense/', include('Apps.incomeExpence.urls', namespace="incomeExpense")),
    path('offender/', include('Apps.offender.urls')),
    path('complaint/', include('Apps.complaints.urls')),
    path('wood/', include('Apps.wood.urls', namespace="wood")),
    path('employee/', include('Apps.report.urls', namespace="report")),
    path('', homeView.as_view(), name="home")
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/employees/models.py
from django.db import models
from django.utils.text import slugify
from Apps.core.models import ForestArea, DESIGNATION
# Create your models here.




class EMPLOYEE(models.Model):
    
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=30, blank=False, null=False, unique=True)
    address = models.TextField(max_length=80)
    contact = models.CharField(max_length=15)
    image = models.ImageField(upload_to="employee/images/")
    designation = models.ForeignKey(to=DESIGNATION, on_delete=models.CASCADE)
    
    def __str__(self):
        
        return self.name
    


class VISIT(models.Model):
    
    forestArea = models.ForeignKey(to=ForestArea, on_delete=models.CASCADE, related_name="visits")
    date = models.DateField()
    description = models.TextField()
    employees = models.ManyToManyField(to=EMPLOYEE, related_name="visits")

Apps/employees/forms.py
from django import forms


from .models import EMPLOYEE, VISIT
from crispy_forms.helper import FormHelper

class empForm(forms.ModelForm):
    
    class Meta:
        model = EMPLOYEE
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False

        self.fields['contact'].widget = forms.TextInput(attrs={'id':'phone', "maxlength":"11"})
        self.fields['email'].widget = forms.EmailInput(attrs={'id':'email', "maxlength":"30"})
        
        
        
"""
-<( === === === === === === === === === === === === VISIT  === === === === === === === === === === === === )>-
"""
class visitForm(forms.ModelForm):
    
    class Meta:
        model = VISIT
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.fields['date'].widget = forms.DateInput(attrs={'type':'date'})
        self.fields['employees'] = forms.ModelMultipleChoiceField(queryset=EMPLOYEE.objects.all(),widget=forms.CheckboxSelectMultiple)

Apps/employees/views.py
from django.shortcuts import render,HttpResponse
from .forms import empForm, visitForm
from .models import EMPLOYEE, VISIT
from django.views import View
from django.views.generic import ListView
from django.contrib import messages
from time import sleep
from django.http import Http404
from django.core.paginator import Paginator
from django.db.models import Q
from render_block import render_block_to_string
from django.shortcuts import get_object_or_404
from django.contrib.auth.hashers import check_password
from django.db import transaction
from Apps.core.views import hx_Redirect
from Apps.core.models import ForestArea
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def get_template(request, name, path="employee"):
    
    if request.htmx:
        return f'{path}/partials/{name}.html'
    
    return f'{path}/{name}.html'


"""
EMPLOYEE CREATE VIEW
"""
class empAddView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        context = {'form': empForm(),'heading':'Add Employee'}
        template = get_template(request, 'emp_add')
        return render(request,template, context )
    
    
    def post(self, request):
        
        
        form = empForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            
            emp = form.save()
            form = empForm()
            
            messages.success(request, "Employee Addedd Successfully")
            
            return hx_Redirect("employee:empList")
        else:
            messages.error(request, "Please Correct the error bellow")
        
        template = get_template(request, 'emp_add')
        
        context = {'form': form}
        return render(request,template, context)
    
    
"""
EMPLOYEE LIST VIEW
"""
class empListView(LoginRequiredMixin,ListView):
    
    model = EMPLOYEE
    context_object_name = 'employees'
    paginate_by = 10
    paginate_orphans = 0
    
    def get_template_names(self): return get_template(self.request, 'emp_list')
    
    def get_queryset(self):
        return EMPLOYEE.objects.all()
    
    def paginate_queryset(self, queryset, page_size):
        
        try:
            
            return super(empListView, self).paginate_queryset(queryset, page_size)
        except Http404:
            
            self.kwargs['page'] = 1
            return super(empListView, self).paginate_queryset(queryset, page_size)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["isSearch"] = False
        return context


"""
EMPLOYEE Search VIEW
"""
class empSearchView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        page_number = request.GET.get('page', 1)
        query = request.GET.get('query')
        
        if query is None:
            query = ""
        
        employees = EMPLOYEE.objects.filter(Q(name__istartswith=query) | Q(email__istartswith=query) | Q(contact__istartswith=query)).order_by('pk')
        paginator = Paginator(employees, per_page=10)
        
        
        
        page = paginator.get_page(page_number)
        
        context={
            
            'employees': page.object_list,
            'page_obj': page,
            'isSearch': True
        
        }
        
        response = render_block_to_string(get_template(request,'emp_list'), 'table', context)
        
        
        return HttpResponse(response)
    
"""
EMPLOYEE Udate VIEW
"""
class empUpdateView(LoginRequiredMixin,View):
    
        

    def get(self, request, pk):
        
        employee = get_object_or_404(EMPLOYEE, pk=pk)
        form = empForm(instance=employee)
        context = {'form':form, 'heading':'Update Employee','isUpdate':True, 'object': employee}
        template_name = get_template(request, 'emp_add')
        
        return render(request, template_name, context)
    
    def post(self, request, pk):
        
        employee = get_object_or_404(EMPLOYEE, pk=pk)
        form = empForm(instance=employee, data=request.POST, files=request.FILES)
        
        if form.is_valid():
            
            employee = form.save()
            messages.success(request, f'{employee} Update Successfully')
            return hx_Redirect("employee:empList")
        else:
            messages.error(request, 'Please correct the Error Bellow')
        
        context = {'form':form, 'heading':'Update Employee','isUpdate':True, 'object': employee}
        template_name = get_template(request, 'emp_add')
        
        return render(request,template_name, context)


    
"""
EMPLOYEE DELETE VIEW
"""

class empDeleteView(LoginRequiredMixin,View):
    
    def get(self, request, pk):
       
        try:
            
            employee = get_object_or_404(EMPLOYEE, id=pk)
            
            context = {'object': employee, 'msg': f'Are you sure you want to delete  <strong> <i>{employee.name}</i></strong>? This action cannot be undone.'}
            
            return render(request,get_template(request, 'delete'), context)
        

        except Http404:
            
            
            return render(request, get_template(request, '404')) 
    
    
    
    def post(self, request, pk):
        
        

        employee = get_object_or_404(EMPLOYEE, id=pk)
        
        employee.delete()       
        messages.success(request, "Employee Deleted Successfully")
        context = {
            'isDeleted':True
        }
        return hx_Redirect("employee:empList")
    
    

"""
-<( === === === === === === === === === === === === VISITS  === === === === === === === === === === === === )>-
"""


"""
VISIT CREATE VIEW
"""
class visitAddView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        context = {'form': visitForm(),'heading':'Add Visit'}
        template = get_template(request,path="visit" ,name='visit_add')
        return render(request,template, context )
    
    
    def post(self, request):
        
        form = visitForm(data=request.POST)
        
        if form.is_valid():
            visit = form.save()
            form = visitForm()
            messages.success(request, "Visits Addedd Successfully")
            return hx_Redirect("employee:visitList")
        else:
            messages.error(request, "Please Correct the error bellow")
            
        template = get_template(request,path="visit" ,name='visit_add')
        
        context = {'form': form,'heading':'Add Visit'}
        return render(request,template, context)
    


"""
VISIT LIST VIEW
"""
class visitListView(LoginRequiredMixin,ListView):
    
    model = VISIT
    context_object_name = 'visits'
    paginate_by = 10
    paginate_orphans = 2
    
    def get_template_names(self): return get_template(self.request, name='visit_list', path="visit")
    
    def get_queryset(self):
        return VISIT.objects.all()
    
    def paginate_queryset(self, queryset, page_size):
        
        try:
            
            return super(visitListView, self).paginate_queryset(queryset, page_size)
        except Http404:
            
            self.kwargs['page'] = 1
            return super(visitListView, self).paginate_queryset(queryset, page_size)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["isSearch"] = False
        context["areas"] = ForestArea.objects.all()
        return context
    


"""
VISIT UPDATE VIEW
"""
class visitUpdateView(LoginRequiredMixin,View):
    
        

    def get(self, request, pk):
        
        visit = get_object_or_404(VISIT, pk=pk)
        form = visitForm(instance=visit)
    
        context = {'form':form, 'heading':'Update Visits',
                   'isUpdate':True, 
                   'object': visit,
                   }
        template_name = get_template(request, name='visit_add', path="visit")
        
        return render(request, template_name, context)
    
    def post(self, request, pk):
        
        visit = get_object_or_404(VISIT, pk=pk)
        form = visitForm(instance=visit, data=request.POST)

        if form.is_valid():
            
            visit = form.save()                
                
            messages.success(request, f'{visit} Update Successfully')
            return hx_Redirect("employee:visitList")
        else:
            messages.error(request, 'Please correct the Error Bellow')
            
        
        
        context = {'form':form, 'heading':'Update Visit',
                   'isUpdate':True,
                   'object': visit
                   }
        
        template_name = get_template(request, 'visit_add', path="visit")
        
        return render(request,template_name, context)



"""
VISTI DELETE VIEW
"""

class visitDeleteView(LoginRequiredMixin,View):
    
    def get(self, request, pk):
       
        try:
            
            visit = get_object_or_404(VISIT, pk=pk)
            
            context = {'object': visit, 'msg': f'Are you sure you want to delete  <strong> <i>{visit}</i></strong>? This action cannot be undone.'}
            
            return render(request,get_template(request, 'delete',path="visit"), context)
        

        except Http404:
            
            return render(request, get_template(request, '404', path="visit")) 
    
    
    
    def post(self, request, pk):
        
        visit = get_object_or_404(VISIT, pk=pk)
        visit.delete()
        messages.success(request, "Visit Deleted Successfully")
        context = {
            'isDeleted':True
        }
        return hx_Redirect("employee:visitList")
        # return render(request, get_template(request, 'delete', path="visit"), context)

Apps/employees/templates/visit/partials/visit_add.html
{% load crispy_forms_tags %} {% load static %} {% include "utils/messages.html"%}



<div class="content container-fluid">
  <div class="page-header">
    <div class="row">
      <div class="col-sm-12">
        <div class="page-sub-header">
          <h3 class="page-title">{{heading}}</h3>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a
                href="#"
                hx-target="#MDI"
                hx-push-url="{% url 'employee:visitList' %}"
                hx-get="{% url 'employee:visitList' %}"
                >Vists List</a
              >
            </li>
            <li class="breadcrumb-item active">
              {% if isUpdate %} Visit Update {% else %} Visit Add {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header mb-3">
          <h5 class="card-title">Enter Visit Information</h5>
        </div>
        <div class="card-body">
<style>
  .employees{
    max-height:300px;
    border: 1px solid #CED4DA;
    width:100%;
    padding: .5em;
    border-radius: 5px;
    overflow-y: scroll;
  }
</style>



          <form action="." hx-target="#MDI"{% if isUpdate %} hx-post="{% url 'employee:visitUpdate' object.pk %}"
            {% else %}
            hx-post="{% url 'employee:visitAdd' %}"
            {% endif %}
          >
            {% csrf_token %}
            <div class="row">
              <div class="col-xl-12">
                <div class="form-group row">
                  <label class="col-lg-3 col-form-label"
                    >{{form.forestArea.label}}</label
                  >
                  <div class="col-lg-9">
                    {{form.forestArea|as_crispy_field}}
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group row">
                  <label class="col-lg-3 col-form-label"
                    >{{form.date.label}}</label
                  >
                  <div class="col-lg-3">{{form.date|as_crispy_field}}</div>
                </div>
              </div>
              <div class="col-xl-12">
                <div class="form-group row">
                  <label class="col-lg-3 col-form-label"
                    >{{form.employees.label}}</label
                  >
                  <div class="col-lg-9">
                   <div class="employees">
                    {{form.employees|as_crispy_field}}
                   </div>
                  </div>
                </div>
              </div>

              <div class="col-xl-12">
                <div class="form-group row">
                  <label class="col-lg-3 col-form-label"
                    >{{form.description.label}}</label
                  >
                  <div class="col-lg-9">
                    {{form.description|as_crispy_field}}
                  </div>
                </div>
              </div>
            </div>

            <div class="text-end">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

  {% if isUpdate %}
    let a = document.querySelector(".text-break a");
    a.setAttribute("target","_blank");
  {% endif %}
</script>

Apps/employees/templates/visit/partials/visit_list.html
<div class="content container-fluid">
  <div class="page-header">
    <div class="row">
      <div class="col-sm-12">
        <div class="page-sub-header">
          <h3 class="page-title">Visit</h3>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li class="breadcrumb-item active">Visit</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- === TABLE === -->

  <div class="row">
    <div class="col-sm-12">
      <div class="card card-table comman-shadow">
        <div class="card-body">
          <div class="page-header">
            <div class="row align-items-center">
              <div class="col">
                <div class="m-0 top-nav-search">
                    <form>
                        <input type="text" id="search" class="form-control" placeholder="Search here">
                        <button hx-vals="js:{'query': get_search_val()}"  hx-get="{% url 'employee:empSearch' %}"   hx-target="#tableMDI" class="btn" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                    
                </div>
              </div>
              <div class="col-auto text-end float-end ms-auto download-grp">
                  <button class="btn btn-secondary" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Print
                  </button>
                <a href="#" hx-target="#MDI" hx-push-url="{% url 'employee:visitAdd' %}" hx-get="{% url 'employee:visitAdd' %}" class="btn btn-primary"
                  ><i class="fas fa-plus"></i
                ></a>
              </div>
            </div>
          </div>
        <div id="tableMDI">
            {% block table %}
          <div class="table-responsive">
            <div
              id="DataTables_Table_0_wrapper"
              class="dataTables_wrapper dt-bootstrap4 no-footer"
            >
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table class="table border-0 star-student table-hover table-center mb-0  no-footer" role="grid">
                    <thead class="">
                      <tr role="row">
                        <th>#</th>
                        <th>Area </th>
                        <th>Date </th>
                        <th>Description </th>
                        <th class="text-end">Action </th>
                      </tr>
                    </thead>
                    <tbody>
                        
                        {% for visit in visits %}
                            <tr role="row" class="odd">
                                <td>{{forloop.counter}}</td>
                                <td>{{visit.forestArea}}</td>
                                <td>{{visit.date|date}}</td>
                                <td>{{visit.description}}</td>
                                <td class="text-end">
                                <div class="actions">
                                    <a
                                    href="javascript:;"
                                    class="btn btn-sm bg-success-light me-2"
                                    hx-get="{% url 'employee:visitDelete' visit.pk %}"
                                    hx-push-url="{% url 'employee:visitDelete' visit.pk %}"
                                    hx-target="#MDI"
                                    >
                                    <i class="feather-trash"></i>
                                    </a>
                                    <a
                                    href="#"
                                    class="btn btn-sm bg-danger-light"
                                    hx-get="{% url 'employee:visitUpdate' visit.pk %}"
                                    hx-push-url="{% url 'employee:visitUpdate' visit.pk %}"
                                    hx-target="#MDI"
                                    >
                                    <i class="feather-edit"></i>
                                    </a>
                                </div>
                                </td> 
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="row">
                
                            <!-- Pagination -->
                        {% if not isSearch %}
                        <div class="col-12 d-flex justify-content-end my-3">
                            <nav>
                                <ul class="pagination">
                                
                                
                                {% if  page_obj.has_previous %}
                                    <li class="paginate_button  page-item ">
                                    <a class="page-link "  href="#"  hx-push-url="{% url 'employee:empList' %}?page={{page_obj.previous_page_number }}" hx-get="{% url 'employee:empList' %}?page={{page_obj.previous_page_number }}" hx-target="#MDI" hx-swap="innerHTML" tabindex="-1" aria-disabled="true">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="paginate_button  page-item disabled">
                                    <a class="page-link " href="#" tabindex="-1" aria-disabled="true">Previous</a>
                                    </li>
                                {% endif %}
                                
                                
                                {% for page in page_obj.paginator %}


                                    {% if page.number < 5 and  page_obj.number < 5 %}
                                    
                                    <li class="paginate_button  page-item   {% if page.number == page_obj.number %} active {% endif %} ">
                                        <a class="page-link "  href="#"  hx-push-url="{% url 'employee:empList' %}?page={{page.number}}" hx-get="{% url 'employee:empList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                    </li> 
                                    {% endif %}
                                    

                                    {% if page.number >= 5 and page.number == page_obj.number %}
                                    
                                    <li class="paginate_button  page-item ">
                                    <a class="page-link " href="#"  hx-push-url="{% url 'employee:empList' %}?page=1" hx-get="{% url 'employee:empList' %}?page={{1}}" hx-target="#MDI" hx-swap="innerHTML">1</a>
                                    </li>

                                    <li class=" paginate_button  page-item disabled">
                                        <a class="page-link " href="#">...</a>
                                    </li>
                                    
                                    <li class=" paginate_button page-item ">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'employee:empList' %}?page={{page.number}}" hx-get="{% url 'employee:empList' %}?page={{page_obj.number|add:-1}}" hx-target="#MDI" hx-swap="innerHTML">{{page_obj.number|add:-1 }}</a>
                                    </li>
                                    
                                    <li class=" paginate_button page-item {% if page.number == page_obj.number %} active {% endif %} ">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'employee:empList' %}?page={{page.number}}" hx-get="{% url 'employee:empList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                    </li>
                                    
                                    {% if page_obj.number < page_obj.paginator.num_pages %}
                                    <li class=" paginate_button  page-item">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'employee:empList' %}?page={{page.number}}" hx-get="{% url 'employee:empList' %}?page={{page_obj.number|add:1}}" hx-target="#MDI" hx-swap="innerHTML">{{page_obj.number|add:1 }}</a>
                                    </li>
                                    {% endif %}
                                    
                                    
                                    {% endif %}
                                    
                                    
                                    {% if forloop.last and  page.number != page_obj.number and page_obj.number|add:1 < page_obj.paginator.num_pages %}
                                    <li class="paginate_button  page-item disabled">
                                        <a class="page-link" href="#">...</a>
                                    </li>
                                    
                                        <li class="paginate_button  page-item">
                                        <a class="page-link "  href="#" hx-push-url="{% url 'employee:empList' %}?page={{page.number}}" hx-get="{% url 'employee:empList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                        </li>
                                    {% endif %}
                                    
                                    
                                {% endfor %}
                                    
                                
                                
                                {% if page_obj.has_next %}
                                    <li class=" paginate_button page-item">
                                    <a class="page-link "  href="#" hx-target="#MDI" hx-push-url="{% url 'employee:empList' %}?page={{page_obj.next_page_number}}" hx-get="{% url 'employee:empList' %}?page={{page_obj.next_page_number}}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="paginate_button  page-item disabled">
                                        <a class="page-link" href="#">Next</a>
                                    </li>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% else %}
                        {% include "employee/partials/search_pagination.html" %}
                    {% endif %}

                    {% comment %} {% include "utils/list_icons.html" %} {% endcomment %}
              </div>

              </div>
            </div>
          </div>

          


          {% endblock table %}
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'utils/messages.html' %}
{% include 'utils/changeUrl.html' %}
<script>
changeURL('{% url "employee:visitList" %}')
</script>


<script>
  
    function get_search_val(){
  
      let search = document.getElementById('search').value
      
      return search
    
    }
  </script>




<style>
  .printModel .input-group .modelInput {
  width: 100%;
  margin-bottom: .5rem;
  } 
</style>
<!-- Modal -->
<div class="modal fade printModel" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Print Report</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <div class="modal-body">
        <form action="{% url 'report:visitReport' %}"  class="input-group" method="post" >
          {% csrf_token %}
          <div class="modelInput">
            <label for="name">Select Area</label>
            <select class="form-select form-control" aria-label="Default select example" name="area" required>
             {% for area in areas %}
              <option value="" selected>----</option>
              <option value="{{area.pk}}">{{area.name}}</option>
              {% endfor %}
            </select>
          </div>

          <div class="modelInput">
            <label for="name">From</label>
            <input type="date" class="form-control" name="fromDate" required>
          </div>

          <div class="modelInput">
            <label for="name">to</label>
            <input type="date" class="form-control" name="toDate" required>
          </div>

          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Print</button>
      </div>
    </form>

    </div>
  </div>
</div>