Apps/core/urls.py
from django.urls import path
from . import views
app_name = "core"

urlpatterns = [
    
    path('area/list/', views.areaListView.as_view(), name="areaList"),
    path('area/add/', views.areaAddView.as_view(), name="areaAdd"),
    path('area/search/', views.areaSearchView.as_view(), name="areaSearch"),
    path('area/update/<slug:slug>/', views.areaUpdateView.as_view(), name="areaUpdate"),
    path('area/delete/<slug:slug>/', views.areaDeleteView.as_view(), name="areaDelete"),
    
    
    # TREE SPECIE PATHS
    
    path('specie/list/', views.specieListView.as_view(), name="specieList"),
    path('specie/add/', views.specieAddView.as_view(), name="specieAdd"),
    path('specie/search/', views.specieSearchView.as_view(), name="specieSearch"),
    path('specie/update/<slug:slug>/', views.specieUpdateView.as_view(), name="specieUpdate"),
    path('specie/delete/<slug:slug>/', views.specieDeleteView.as_view(), name="specieDelete"),
    
    
     # CUSTOMER PATHS
     
    path('customer/list/', views.customerListView.as_view(), name="customerList"),
    path('customer/add/', views.customerAddView.as_view(), name="customerAdd"),
    path('customer/search/', views.customerSearchView.as_view(), name="customerSearch"),
    path('customer/update/<int:id>/', views.customerUpdateView.as_view(), name="customerUpdate"),
    path('customer/delete/<int:id>/', views.customerDeleteView.as_view(), name="customerDelete"),


      # CUSTOMER PATHS
     
    path('designation/list/', views.designationListView.as_view(), name="designationList"),
    path('designation/add/', views.designationAddView.as_view(), name="designationAdd"),
    path('designation/search/', views.designationSearchView.as_view(), name="designationSearch"),
    path('designation/update/<int:id>/', views.designationUpdateView.as_view(), name="designationUpdate"),
    path('designation/delete/<int:id>/', views.designationDeleteView.as_view(), name="designationDelete"),
]

FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='account')),
    path('account/', include('allauth.urls')),
    path('employee/', include('Apps.employees.urls', namespace="employees")),
    path('core/', include('Apps.core.urls', namespace="core")),
    path('income-expense/', include('Apps.incomeExpence.urls', namespace="incomeExpense")),
    path('offender/', include('Apps.offender.urls')),
    path('complaint/', include('Apps.complaints.urls')),
    path('wood/', include('Apps.wood.urls', namespace="wood")),
    path('employee/', include('Apps.report.urls', namespace="report")),
    path('', homeView.as_view(), name="home")
    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/core/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.



class ForestArea(models.Model):
    
    name = models.CharField(max_length = 30, unique=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField(max_length=200)
    slug = models.SlugField(unique=True,blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ForestArea, self).save(args, kwargs)
    
    class Meta:
        ordering = ['pk']


class TreeSpecies(models.Model):
    
    name = models.CharField(max_length = 30, unique=True)
    description = models.TextField(max_length=200)
    slug = models.SlugField(unique=True,blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        
        
        self.slug = slugify(self.name)
        super(TreeSpecies, self).save(args, kwargs)
    
    class Meta:
        ordering = ['pk']

class CUSTOMER(models.Model):
    
    name = models.CharField(max_length=30)
    address = models.TextField(max_length=80)
    contact = models.CharField(max_length=11)
    image = models.ImageField(upload_to="customer/images/")
    
    def __str__(self):
        
        return self.name
    
    class Meta:
        ordering = ['pk']
    

class DESIGNATION(models.Model):

    name = models.CharField(max_length=30)

    
    def __str__(self):
        
        return self.name

Apps/core/forms.py
from django import forms
from .models import ForestArea, TreeSpecies, CUSTOMER, DESIGNATION
from crispy_forms.helper import FormHelper

class forestAreaForm(forms.ModelForm):
    
    class Meta:
        model = ForestArea
        fields = '__all__'
        exclude = ['slug']
        
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False


class specieForm(forms.ModelForm):
    
    class Meta:
        model = TreeSpecies
        fields = '__all__'
        exclude = ['slug']
        
    def __init__(self, *args, **kwargs):
        
        super(specieForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False


class customerForm(forms.ModelForm):
      
    class Meta:
        model = CUSTOMER
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        
        super(customerForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False


class designationForm(forms.ModelForm):
    
    class Meta:
        model = DESIGNATION
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_show_labels = False

Apps/core/views.py
from django.shortcuts import render,HttpResponse
from .forms import forestAreaForm, specieForm, customerForm, designationForm
from .models import ForestArea, TreeSpecies, CUSTOMER, DESIGNATION
from django.views import View
from django.views.generic import ListView, DeleteView
from django.contrib import messages
from time import sleep
from django.http import Http404
from django.core.paginator import Paginator
from django.db.models import Q
from render_block import render_block_to_string
from django.shortcuts import get_object_or_404
from django.contrib.auth.hashers import check_password
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def get_template(request, name, path="forestArea"):
    
    if request.htmx:
        return f'{path}/partials/{name}.html'
    
    return f'{path}/{name}.html'

def hx_Redirect(url):
    resp = HttpResponseRedirect(_(url))
    resp['HX-Redirect'] = _(url)
    return resp


"""
Area CREATE VIEW
"""
class areaAddView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        context = {'form': forestAreaForm(),'heading':'Add Area'}
        template = get_template(request, 'area_add')
        return render(request,template, context )
    
    
    def post(self, request):
        
        
        form = forestAreaForm(data=request.POST)
        if form.is_valid():
            
            emp = form.save()
            form = forestAreaForm()
            
            messages.success(request, "Area Addedd Successfully")
            return hx_Redirect("core:areaList")
        else:
            messages.error(request, "Please Correct the error bellow")
        
        template = get_template(request, 'area_add')
        
        context = {'form': form}
        return render(request,template, context)
    
    
"""
AREA LIST VIEW
"""
class areaListView(LoginRequiredMixin,ListView):
    
    model = ForestArea
    context_object_name = 'areas'
    paginate_by = 10
    paginate_orphans = 0
    
    def get_template_names(self): return get_template(self.request, 'area_list')
    
    def get_queryset(self):
        return ForestArea.objects.all()
    
    def paginate_queryset(self, queryset, page_size):
        
        try:
            
            return super(areaListView, self).paginate_queryset(queryset, page_size)
        except Http404:
            
            self.kwargs['page'] = 1
            return super(areaListView, self).paginate_queryset(queryset, page_size)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["isSearch"] = False
        return context


"""
Area Search VIEW
"""
class areaSearchView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        page_number = request.GET.get('page', 1)
        query = request.GET.get('query')
        
        if query is None:
            query = ""
        
        areas = ForestArea.objects.filter(Q(name__istartswith=query)).order_by('pk')
        paginator = Paginator(areas, per_page=10)
        
        
        
        page = paginator.get_page(page_number)
        
        context={
            
            'areas': page.object_list,
            'page_obj': page,
            'isSearch': True
        
        }
        
        response = render_block_to_string(get_template(request,'area_list'), 'table', context)
        
        
        return HttpResponse(response)
    
"""
Area Udate VIEW
"""
class areaUpdateView(LoginRequiredMixin,View):
    
        

    def get(self, request, slug):
        
        area = get_object_or_404(ForestArea, slug=slug)
        form = forestAreaForm(instance=area)
        context = {'form':form, 'heading':'Update Area','isUpdate':True, 'object': area}
        template_name = get_template(request, 'area_add')
        
        return render(request, template_name, context)
    
    def post(self, request, slug):
        
        area = get_object_or_404(ForestArea, slug=slug)
        form = forestAreaForm(instance=area, data=request.POST)
        
        if form.is_valid():
            
            area = form.save()
            messages.success(request, f'{area} Update Successfully')
            return hx_Redirect("core:areaList")
        else:
            messages.error(request, 'Please correct the Error Bellow')
        
        context = {'form':form, 'heading':'Update Area','isUpdate':True, 'object': area}
        template_name = get_template(request, 'area_add')
        
        return render(request,template_name, context)


    
"""
Area Delete VIEW
"""

class areaDeleteView(LoginRequiredMixin,View):
    
    def get(self, request, slug):
       
        try:
            
            area = get_object_or_404(ForestArea, slug=slug)
            
            context = {'object': area, 'msg': f'Are you sure you want to delete  <strong> <i>{area.name}</i></strong>? This action cannot be undone.'}
            
            return render(request,get_template(request, 'delete'), context)
        

        except Http404:
            
            
            return render(request, get_template(request, '404')) 
    
    
    
    def post(self, request, slug):
        
        
        
        area = get_object_or_404(ForestArea, slug=slug)

        area.delete()
        messages.success(request, f'{area.name} deleted successfully')

        return hx_Redirect("core:areaList")
        # context = {'isDeleted': True,'msg': f'{area.name} deleted Successfully'}
        # return render(request, get_template(request, 'delete'), context)
    
    

"""
****************************************** TREE SPECIE SECTION ******************************************
"""

"""
Tree Specie CREATE VIEW
"""
class specieAddView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        context = {'form': specieForm(),'heading':'Add Specie'}
        template = get_template(request, 'specie_add', path="treeSpecies")
        return render(request,template, context )
    
    
    def post(self, request):
        
        
        form = specieForm(data=request.POST)
        if form.is_valid():
            
            specie = form.save()
            form = specieForm()
            
            messages.success(request, "Specie Addedd Successfully")
            return hx_Redirect("core:specieList")
        else:
            messages.error(request, "Please Correct the error bellow")
        
        template = get_template(request, 'specie_add', path="treeSpecies")
        
        context = {'form': form}
        return render(request,template, context)
    
    
"""
Tree Specie LIST VIEW
"""
class specieListView(LoginRequiredMixin,ListView):
    
    model = ForestArea
    context_object_name = 'species'
    paginate_by = 10
    paginate_orphans = 0
    
    def get_template_names(self): return get_template(self.request, 'specie_list', path="treeSpecies")
    
    def get_queryset(self):
        return TreeSpecies.objects.all()
    
    def paginate_queryset(self, queryset, page_size):
        
        try:
            
            return super(specieListView, self).paginate_queryset(queryset, page_size)
        except Http404:
            
            self.kwargs['page'] = 1
            return super(specieListView, self).paginate_queryset(queryset, page_size)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["isSearch"] = False
        return context


"""
Tree Specie Search VIEW
"""
class specieSearchView(LoginRequiredMixin,View):
    
    def get(self, request):
        
        page_number = request.GET.get('page', 1)
        query = request.GET.get('query')
        
        if query is None:
            query = ""
        
        species = TreeSpecies.objects.filter(Q(name__istartswith=query)).order_by('pk')
        paginator = Paginator(species, per_page=10)
        
        
        
        page = paginator.get_page(page_number)
        
        context={
            
            'species': page.object_list,
            'page_obj': page,
            'isSearch': True
        
        }
        
        response = render_block_to_string(get_template(request,'specie_list', path="treeSpecies"), 'table', context)
        
        
        return HttpResponse(response)
    
"""
Tree Specie Udate VIEW
"""
class specieUpdateView(LoginRequiredMixin,View):
    
        

    def get(self, request, slug):
        
        specie = get_object_or_404(TreeSpecies, slug=slug)
        form = specieForm(instance=specie)
        context = {'form':form, 'heading':'Update Specie','isUpdate':True, 'object': specie}
        template_name = get_template(request, 'specie_add', path="treeSpecies")
        
        return render(request, template_name, context)
    
    def post(self, request, slug):
        
        specie = get_object_or_404(TreeSpecies, slug=slug)
        form = specieForm(instance=specie, data=request.POST)
        
        if form.is_valid():
            
            specie = form.save()
            messages.success(request, f'{specie} Update Successfully')
            return hx_Redirect("core:specieList")
        else:
            messages.error(request, 'Please correct the Error Bellow')
        
        context = {'form':form, 'heading':'Update Specie','isUpdate':True, 'object': specie}
        template_name = get_template(request, 'specie_add', path="treeSpecies")
        
        return render(request,template_name, context)


    
"""
Tree Specie Delete VIEW
"""

class specieDeleteView(LoginRequiredMixin,View):
    
    def get(self, request, slug):
       
        try:
            
            specie = get_object_or_404(TreeSpecies, slug=slug)
            

Apps/core/templates/treeSpecies/partials/delete.html
{% load static %}
{% include "utils/messages.html" %}



<div class="content container-fluid">

    <div class="page-header">
    <div class="row">
    <div class="col">
    <h3 class="page-title">Delete Confirmation</h3>
    <ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#" hx-target="#MDI" hx-push-url="{% url 'core:specieList' %}" hx-get="{% url 'core:specieList' %}">Tree Specie</a></li>
    <li class="breadcrumb-item active">Tree Specie Delete</li>
    </ul>
    </div>
    </div>
    </div>
    
    <div class="row" style="height:80vh; position: relative;">
    <div class="col-sm-12" style="position: absolute; top:30%; left:50%; transform:translate(-50%,-50%)">
        <p class="card-description text-center">
            {{msg|safe}}
        </p>
  {% if not  isDeleted %}
        <div class="d-flex justify-content-center align-items-center">
            <form action=""   hx-target="#MDI" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger" hx-target="#MDI" hx-push-url="{% url 'core:specieDelete' object.slug %}" hx-post="{% url 'core:specieDelete' object.slug %}" >Confirm Delete</button>
            </form>
            <button class="btn btn-outline-success" hx-target="#MDI" hx-push-url="{% url 'core:specieList' %}" hx-get="{% url 'core:specieList' %}">Go Back</button>
        </div>
        {% else %}
        <div class="d-flex justify-content-center align-items-center">
        <button class="btn btn-outline-success" hx-target="#MDI" hx-push-url="{% url 'core:specieList' %}" hx-get="{% url 'core:specieList' %}">Go Back</button>
        </div>
        {% endif %}
    </div>
    </div>
    </div>



  


 

Apps/core/templates/treeSpecies/partials/specie_add.html
{% load crispy_forms_tags %}
{% load static %}
{% include "utils/messages.html" %}

  <div class="content container-fluid">
    <div class="page-header">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-sub-header">
            <h3 class="page-title">{{heading}}</h3>
            <ul class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="../index.html">Home</a>
                
              </li>
              <li class="breadcrumb-item"><a href="#" hx-target="#MDI" hx-push-url="{% url 'core:specieList' %}" hx-get="{% url 'core:specieList' %}">Tree Specie</a></li>
              <li class="breadcrumb-item active">{% if isUpdate %} Tree Specie Update {% else %} Tree Specie Add {% endif %}</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header mb-3">
            <h5 class="card-title">Enter Specie Information</h5>
          </div>
          <div class="card-body">
            <form action="." hx-target="#MDI" {% if isUpdate %} hx-post="{% url 'core:specieUpdate' object.slug %}" {% else %} hx-post="{% url 'core:specieAdd' %}" {% endif %} >
              {% csrf_token %}
              <div class="row">
                <div class="col-12">
                  <div class="form-group row">
                    <label class="col-lg-3 col-form-label">{{form.name.label}}</label>
                    <div class="col-lg-9">
                      {{form.name|as_crispy_field}}
                    </div>
                  </div>
                </div>

                <div class="col-12">
                  <div class="form-group row">
                    <label class="col-lg-3 col-form-label">{{form.description.label}}</label>
                    <div class="col-lg-9">
                      {{form.description|as_crispy_field}}
                    </div>
                  </div>
                </div>
              </div>

              <div class="text-end">
                <button type="submit"  class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>


  {% include 'utils/acceptOnlyChars.html' %}
  <script>
    acceptOnlyChars(['id_name']);
  </script>

Apps/core/templates/treeSpecies/partials/specie_list.html
{% load fmsTemplateTag %}
<div class="content container-fluid">
  <div class="page-header">
    <div class="row">
      <div class="col-sm-12">
        <div class="page-sub-header">
          <h3 class="page-title">Tree Specie</h3>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active">Tree Specie</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- === TABLE === -->

  <div class="row">
    <div class="col-sm-12">
      <div class="card card-table comman-shadow">
        <div class="card-body">
          <div class="page-header">
            <div class="row align-items-center">
              <div class="col">
                <div class="m-0 top-nav-search">
                    <form>
                        <input type="text" id="search" class="form-control" placeholder="Search here">
                        <button hx-vals="js:{'query': get_search_val()}"  hx-get="{% url 'core:specieSearch' %}"   hx-target="#tableMDI" class="btn" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                    
                </div>
              </div>
              <div class="col-auto text-end float-end ms-auto download-grp">
                <a href="#" hx-target="#MDI" hx-push-url="{% url 'core:specieAdd' %}" hx-get="{% url 'core:specieAdd' %}" class="btn btn-primary"
                  ><i class="fas fa-plus"></i
                ></a>
              </div>
            </div>
          </div>
        <div id="tableMDI">
            {% block table %}
          <div class="table-responsive">
            <div
              id="DataTables_Table_0_wrapper"
              class="dataTables_wrapper dt-bootstrap4 no-footer"
            >
              <div class="row">
                <div class="col-sm-12 col-md-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table class="table border-0 star-student table-hover table-center mb-0  no-footer" role="grid">
                    <thead class="">
                      <tr role="row">
                        
                        <th>#</th>
                        <th>Name </th>
                        <th >Description </th>
                       <th class="text-end">Action </th>
                      </tr>
                    </thead>
                    <tbody>
                        
                        {% for specie in species %}
                            <tr role="row" class="{% if forloop.counter|isOdd %} odd {% else %} even {% endif %}">
                                <td>{{forloop.counter}}</td>
                                
                                <td>{{specie.name}}</td>

                                <td>{{specie.description}}</td>
                            
                                <td class="text-end">
                                <div class="actions">
                                    <a
                                    href="javascript:;"
                                    class="btn btn-sm bg-success-light me-2"
                                    hx-get="{% url 'core:specieDelete' specie.slug %}"
                                    hx-push-url="{% url 'core:specieDelete' specie.slug %}"
                                    hx-target="#MDI"
                                    >
                                    <i class="feather-eye"></i>
                                    </a>
                                    <a
                                    href="#"
                                    class="btn btn-sm bg-danger-light"
                                    hx-get="{% url 'core:specieUpdate' specie.slug %}"
                                    hx-push-url="{% url 'core:specieUpdate' specie.slug %}"
                                    hx-target="#MDI"
                                    >
                                    <i class="feather-edit"></i>
                                    </a>
                                </div>
                                </td>
                            </tr>
                        {% endfor %}
                            

                   
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="row">
                
                            <!-- Pagination -->
                        {% if not isSearch %}
                        <div class="col-12 d-flex justify-content-end my-3">
                            <nav>
                                <ul class="pagination">
                                
                                
                                {% if  page_obj.has_previous %}
                                    <li class="paginate_button  page-item ">
                                    <a class="page-link "  href="#"  hx-push-url="{% url 'core:specieList' %}?page={{page_obj.previous_page_number }}" hx-get="{% url 'core:specieList' %}?page={{page_obj.previous_page_number }}" hx-target="#MDI" hx-swap="innerHTML" tabindex="-1" aria-disabled="true">Previous</a>
                                    </li>
                                    {% else %}
                                    <li class="paginate_button  page-item disabled">
                                    <a class="page-link " href="#" tabindex="-1" aria-disabled="true">Previous</a>
                                    </li>
                                {% endif %}
                                
                                
                                {% for page in page_obj.paginator %}


                                    {% if page.number < 5 and  page_obj.number < 5 %}
                                    
                                    <li class="paginate_button  page-item   {% if page.number == page_obj.number %} active {% endif %} ">
                                        <a class="page-link "  href="#"  hx-push-url="{% url 'core:specieList' %}?page={{page.number}}" hx-get="{% url 'core:specieList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                    </li> 
                                    {% endif %}
                                    

                                    {% if page.number >= 5 and page.number == page_obj.number %}
                                    
                                    <li class="paginate_button  page-item ">
                                    <a class="page-link " href="#"  hx-push-url="{% url 'core:specieList' %}?page=1" hx-get="{% url 'core:specieList' %}?page={{1}}" hx-target="#MDI" hx-swap="innerHTML">1</a>
                                    </li>

                                    <li class=" paginate_button  page-item disabled">
                                        <a class="page-link " href="#">...</a>
                                    </li>
                                    
                                    <li class=" paginate_button page-item ">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'core:specieList' %}?page={{page.number}}" hx-get="{% url 'core:specieList' %}?page={{page_obj.number|add:-1}}" hx-target="#MDI" hx-swap="innerHTML">{{page_obj.number|add:-1 }}</a>
                                    </li>
                                    
                                    <li class=" paginate_button page-item {% if page.number == page_obj.number %} active {% endif %} ">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'core:specieList' %}?page={{page.number}}" hx-get="{% url 'core:specieList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                    </li>
                                    
                                    {% if page_obj.number < page_obj.paginator.num_pages %}
                                    <li class=" paginate_button  page-item">
                                        <a class="page-link " href="#"  hx-push-url="{% url 'core:specieList' %}?page={{page.number}}" hx-get="{% url 'core:specieList' %}?page={{page_obj.number|add:1}}" hx-target="#MDI" hx-swap="innerHTML">{{page_obj.number|add:1 }}</a>
                                    </li>
                                    {% endif %}
                                    
                                    
                                    {% endif %}
                                    
                                    
                                    {% if forloop.last and  page.number != page_obj.number and page_obj.number|add:1 < page_obj.paginator.num_pages %}
                                    <li class="paginate_button  page-item disabled">
                                        <a class="page-link" href="#">...</a>
                                    </li>
                                    
                                        <li class="paginate_button  page-item">
                                        <a class="page-link "  href="#" hx-push-url="{% url 'core:specieList' %}?page={{page.number}}" hx-get="{% url 'core:specieList' %}?page={{page.number}}" hx-target="#MDI" hx-swap="innerHTML">{{page.number }}</a>
                                        </li>
                                    {% endif %}
                                    
                                    
                                {% endfor %}
                                    
                                
                                
                                {% if page_obj.has_next %}
                                    <li class=" paginate_button page-item">
                                    <a class="page-link "  href="#" hx-target="#MDI" hx-push-url="{% url 'core:specieList' %}?page={{page_obj.next_page_number}}" hx-get="{% url 'core:specieList' %}?page={{page_obj.next_page_number}}">Next</a>
                                    </li>
                                {% else %}
                                    <li class="paginate_button  page-item disabled">
                                        <a class="page-link" href="#">Next</a>
                                    </li>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% else %}
                        {% include "forestArea/partials/search_pagination.html" %}
                    {% endif %}

                    {% comment %} {% include "utils/list_icons.html" %} {% endcomment %}
              </div>

              </div>
            </div>
          </div>

          


          {% endblock table %}
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'utils/messages.html' %}
{% include 'utils/changeUrl.html' %}
<script>
changeURL('{% url "core:specieList" %}')
</script>

<script>
  
    function get_search_val(){
  
      let search = document.getElementById('search').value
      
      return search
    
    }
  </script>